using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace api.Models
{
    [Table("users")]
    public class User
    {
        [Key]
        [Column("user_id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-incrementing ID
        public int UserId { get; set; }

        [Column("username")]
        [StringLength(50)]
        [Required] // Username must be provided
        public string Username { get; set; }

        [Column("email")]
        [StringLength(100)]
        [Required] // Email must be provided
        public string Email { get; set; }

        [Column("profile_picture")]
        [StringLength(255)]
        public string ProfilePicture { get; set; } // Optional

        [Column("bio")]
        public string Bio { get; set; } // Optional

        [Column("date_of_birth")]
        public DateTime? DateOfBirth { get; set; } // Now optional

        [Column("created_at")]
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)] // Automatically generated by DB
        public DateTime CreatedAt { get; set; }
    }
}
